FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as base
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-ef
WORKDIR /app
EXPOSE 5000:5000

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-ef
WORKDIR /src
COPY ["./GestionaryWebsite/GestionaryWebsite.csproj", "./"]
RUN dotnet restore "GestionaryWebsite.csproj"
COPY . .
RUN dotnet build "./GestionaryWebsite" -c Release -o /app

FROM build as publish
RUN dotnet publish "./GestionaryWebsite" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "GestionaryWebsite.dll"]